### ISSUE TITLE
Driver does not work on surface laptop 3

### ISSUE THREAD

**Issue by dooman17** [displaylink-rpm/displaylink-rpm#148]
I am running fedora 32 on my surface laptop 3 and this laptop requires a specific linux kernel to work correctly. As far as I can tell, it is 5.8.15-1 with support for the keyboard, touchpad, and touchscreen. My USB monitor does not work on this version. However, it does work on 5.8.15-201, but on that version I cannot use the keyboard, mouse, or touchpad. 

secureboot is disabled

This is the kernel im using
https://github.com/linux-surface/linux-surface

attempting to start the displaylink service with `sudo systemctl start displaylink` gives
```
Job for displaylink.service failed because the control process exited with error code.
See "systemctl status displaylink.service" and "journalctl -xe" for details.
```

`systemctl status displaylink.service` gives
```
Job for displaylink.service failed because the control process exited with error code.
See "systemctl status displaylink.service" and "journalctl -xe" for details.

```
`journalctl -xe` gives
```
Oct 18 21:46:11 localhost.localdomain systemd[1]: displaylink.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- An ExecStartPre= process belonging to unit displaylink.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Oct 18 21:46:11 localhost.localdomain systemd[1]: displaylink.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit displaylink.service has entered the 'failed' state with result 'exit-code'.
Oct 18 21:46:11 localhost.localdomain systemd[1]: Failed to start DisplayLink Manager Service.
-- Subject: A start job for unit displaylink.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit displaylink.service has finished with a failure.
-- 
-- The job identifier is 15419 and the job result is failed.
Oct 18 21:46:11 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init>

```

**Comment by elguero** [comment]
I would say you are venturing into uncharted waters and we might not be able to provide the proper support here.

I took a quick look at the repo you referenced to see if I could think of any quick suggestions. They mention right off the bat that there are hardware caveats.  I am not sure how much the community can support hardware designed for Windows 10 but running a special distro of Fedora on it.  I think you would be better served in working with the linux-surface community since they will be more familiar with the caveats and the patches they are creating for the kernel to get the distro working on that specific hardware.

Perhaps, once the linux-surface community updates to a newer kernel your problem will be resolved.  All this community, displaylink-rpm, does is re-package the DisplayLink release so that it can be installed on Fedora or CentOS.  I do not think we can take on support of custom kernels.
