### ISSUE TITLE
How to install diplaylink on Fedora Silverblue ?

### ISSUE THREAD

**Issue by hiengyen** [displaylink-rpm/displaylink-rpm#267]
* Are you using the latest DisplayLink driver?
    
  * Are you using the latest EVDI module?
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    
  * Is this issue related to evdi/kernel?
    
  * Is this issue related to DisplayLinkManager?
    
  * If you are having an issue upgrading, have you tried to do a clean install of the driver?
    

  * Fedora / CentOS Stream / Rocky Linux / AlmaLinux OS
  * Version
  * Kernel version `(uname -a)`

  * `/var/log/displaylink/displaylink.log`
  * `/var/lib/dkms/evdi/kernel-[version]/log/make.log`

**Comment by sabinich** [comment]
@hiengyen Hi! check this up for building and loading custom kernel (in case with evdi) on immutable system: https://github.com/senz/silverblue-modules/tree/git-version-support?tab=readme-ov-file#evdi
Also you need a little bit modify `/usr/lib/systemd/system/displaylink-driver.service`, because it try to load module on "normal" system ;)
I've checked it by hand (`sudo /usr/libexec/displaylink/DisplayLinkManager`) and it works well.
